name: zebra_rfid_flutter_demo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  another_flushbar: ^1.12.30
  app_settings: ^5.1.1
  async: ^2.11.0
  audioplayers: ^5.2.1
  collection: ^1.17.1
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.3
  currency_text_input_formatter: ^2.2.1
  device_info_plus: ^9.1.2
  dio: ^5.2.1+1
  dotted_border: ^2.0.0+3
  # This package doesn't look maintained, plan to replace it
  drag_and_drop_lists: # Temporary Flutter 3.22 fix https://github.com/philip-brink/DragAndDropLists/pull/98
    git:
      url: git@github.com:dmitry-comet/DragAndDropLists.git
      ref: 04715d15ec1a679cf0bc4fcfada75155c9443388
  drift: ^2.18.0
  file_picker: 8.0.7
  firebase_analytics: ^10.10.7
  firebase_core: ^2.32.0
  firebase_crashlytics: ^3.5.7
  firebase_messaging: ^14.9.4
  flutter:
    sdk: flutter
  flutter_advanced_calendar:
    git:
      url: git@github.com:itsJoKr/flutter_advanced_calendar.git
      ref: db19135d78a945f69d8aaa4cbd42c65ea2e6a7fe
  flutter_animate: ^4.2.0+1
  # Lib doesn't work for Android 14+. This PR addresses it but it hasn't been merged yet
  flutter_barcode_listener: ^0.1.4
#  flutter_broadcasts: # https://github.com/kevlatus/flutter_broadcasts/pull/16
#    git:
#      url: git@github.com:DPohorielov/flutter_broadcasts.git
#      ref: 616eaf91a8d8e1dca70bafe5fecde33164298d77
  flutter_email_sender: ^6.0.3
  flutter_hooks: ^0.20.0
  flutter_local_notifications: ^17.2.2
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.3
  flutter_loggy_dio: ^3.1.0
  flutter_riverpod: ^2.4.10
  flutter_secure_storage: ^8.0.0
  flutter_slidable: ^4.0.0
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.7
  flutter_web_auth_2: ^4.1.0
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^9.0.0
  hand_signature: ^3.0.1
  hooks_riverpod: ^2.5.1
  http: 1.2.1
  image: ^4.1.3
  image_picker: 1.0.8
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.7.1
  local_auth: ^2.3.0
  location: ^7.0.0
  loggy: ^2.0.3
  maps_launcher: ^2.2.1
  mime: ^2.0.0
  modal_bottom_sheet: ^3.0.0-pre
  # There is an issue with running the latest on iOS for both intl_phone_number_input and libphonenumber_plugin
  # https://medium.com/@shahidbangashsi94/fix-for-swift-compiler-error-xcode-cannot-find-type-phonenumberkit-in-scope-b01daad3e452
  intl_phone_number_input:
    git:
      url: https://github.com/igniti0n/intl_phone_number_input.git
      ref: 57137d49b8a3689b191e8b6c451ba880329cd580
  libphonenumber_plugin:
    git:
      url: https://github.com/Shahidbangash/plugin_libphonenumber.git
      ref: main
      path: libphonenumber_plugin
  move_flutter_api:
    git:
      url: git@github.com:movemedical/move-flutter-api.git
      ref: 2025.1-135
  network_logger:
    git:
      url: https://github.com/itsJoKr/flutter-network-logger
      ref: 1744138ebc22c35a73e77720e2d5bf93f2be5a20
  open_file_manager: ^0.0.4
  open_filex: ^4.7.0
  package_info_plus: ^4.1.0
  path: ^1.9.0
  path_provider: ^2.1.1
  power_file_view:
    git:
      url: git@github.com:itsJoKr/flutter_power_file_view.git
      ref: 7df3ec8bfe67b9972ef353efee654b5a0ed9330e
  pubspec_parse: ^1.2.3
  qr_mobile_vision:
    git:
      url: git@github.com:itsJoKr/flutter_qr_mobile_vision.git
      ref: 69d77be93d12cdc69a7bb5087bf50eb7e0fae6d0
  quiver: ^3.2.1
  recase: ^4.1.0
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  settings_ui: ^2.0.2
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  smooth_page_indicator: ^1.1.0
  sqlcipher_flutter_libs: ^0.5.7
  sqlite3: ^2.4.3
  sticky_headers: ^0.3.0+2
  timezone: ^0.9.4
  url_launcher: ^6.2.6
  uuid: ^4.5.1
  validators: ^3.0.0
  vibration: ^3.1.3
  visibility_detector: ^0.4.0+2
  web_socket_client: ^0.1.0
  external_app_launcher: ^4.0.2
  local_auth_android: ^1.0.46
  local_auth_ios: ^1.1.7
  app_badge_plus: ^1.1.6
  rxdart: ^0.28.0
  permission_handler: ^11.4.0

dependency_overrides:
  analyzer: ^6.3.0
  custom_lint_core: ^0.6.6
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.14
  change_app_package_name: ^1.2.0
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  riverpod_generator: ^2.4.0
  #  riverpod_lint: ^2.1.0
  test: ^1.24.3

flutter:
  uses-material-design: true
  generate: true